In [2]:
#singular value decomposition

from scipy import linalg
import numpy as np
m=np.array([[1,2],[3,4]])
x,y,z=linalg.svd(m)
z,y,x

(array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]))

In [3]:
#eigen value and eigen vector

from scipy import linalg
import numpy as np
M=np.array([[1,2],[3,4]])
val,vect=linalg.eig(m)
val
vect

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [6]:
#norms

from scipy import linalg
import numpy as np
x=np.array([1,2])
a=linalg.norm(x)  #l2
b=linalg.norm(x,1) #l1
a,b

(2.23606797749979, 3.0)