In [3]:
#cdf

from scipy.stats import norm
import numpy as np
arr=np.array([1,2,3])
norm.cdf(arr)


array([0.84134475, 0.97724987, 0.9986501 ])

In [8]:
#circmean

from scipy.stats import circmean
import numpy as np
arr=np.array([1,2,3,4])
circmean(arr,high=4,low=0)

3.0

In [10]:
#describe

from scipy import stats
import numpy
arr=numpy.array([1,2,3,4])
stats.describe(arr)

DescribeResult(nobs=4, minmax=(1, 4), mean=2.5, variance=1.6666666666666665, skewness=0.0, kurtosis=-1.36)

In [15]:
#variation

from scipy import stats
import numpy
arr=numpy.array([1,2,3,4])
stats.variation(arr)

0.447213595499958

In [17]:
#kurtosis

from scipy import stats 
ds=stats.norm.rvs(size=88)
stats.kurtosis(ds)

0.0851729862513868

In [19]:
#rank

from scipy import stats
array=([1,2,3,4])
stats.rankdata(array)

array([1., 2., 3., 4.])

In [20]:
#zscore

from scipy import stats
ds=([1,2,3,4,5])
stats.zscore(ds)

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])