In [2]:
#row vice
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1) #axis 1 for row
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [3]:
#column vice
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=0)#axis 0 for column
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
#stack
import numpy as np
arr1=([[1,2],[4,5]])
arr2=([[7,8],[1,2]])
arr=np.stack((arr1,arr2),axis=1)
arr

array([[[1, 2],
        [7, 8]],

       [[4, 5],
        [1, 2]]])

In [6]:
import numpy as np
arr1=([[1,2],[4,5]])
arr2=([[7,8],[1,2]])
arr=np.stack((arr1,arr2),axis=0)
arr

array([[[1, 2],
        [4, 5]],

       [[7, 8],
        [1, 2]]])

In [9]:
#horizontal
import numpy as np
arr1=([[1,2],[4,5]])
arr2=([[7,8],[1,2]])
arr=np.hstack((arr1,arr2))
arr

array([[1, 2, 7, 8],
       [4, 5, 1, 2]])