In [1]:
#dot()

import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([2,4,6,8])
rslt=np.dot(arr1,arr2)
rslt

60

In [2]:
#inner()

import numpy as np
arr1=np.array([[1,2],
              [3,4]])
arr2=np.array([[2,4],
              [6,8]])
rslt=np.inner(arr1,arr2)
rslt

array([[10, 22],
       [22, 50]])

In [3]:
#outer()

import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([2,4,6])
rslt=np.outer(arr1,arr2)
rslt

array([[ 2,  4,  6],
       [ 4,  8, 12],
       [ 6, 12, 18]])

In [5]:
#determinant(det())

import numpy as np
arr=np.array([[1,3],
              [5,7]])  #  [1,3]  = (1*7)-(3*5) =7-15
                        # [5,7]

rslt=np.linalg.det(arr)
rslt

-7.999999999999998

In [6]:
#solve()

import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([2,3])
rslt=np.linalg.solve(arr1,arr2)
rslt

array([-1. ,  1.5])

In [7]:
#inverse inv()

import numpy as np 
arr=np.array([[1,2],[3,4]])
rslt=np.linalg.inv(arr)
rslt

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
#trace()

import numpy as np 
arr=np.array([[1,2,3],[3,4,5],[2,4,6]])
rslt=np.trace(arr)
rslt



11